return {
    "jay-babu/colorscheme-randomizer.nvim",
    dependencies = {
        "altercation/vim-colors-solarized",
        "ayu-theme/ayu-vim",
        "catppuccin/nvim",
        "cocopon/iceberg.vim",
        "dracula/vim",
        "EdenEast/nightfox.nvim",
        "ellisonleao/gruvbox.nvim",
        "folke/tokyonight.nvim",
        "forest-nvim/sequoia.nvim",
        "GertjanReynaert/cobalt2-vim-theme",
        "haishanh/night-owl.vim",
        "jnurmine/Zenburn",
        "JoosepAlviste/palenightfall.nvim",
        "joshdick/onedark.vim",
        "luisiacc/gruvbox-baby",
        "LunarVim/lunar.nvim",
        "mellow-theme/mellow.nvim",
        "nanotech/jellybeans.vim",
        "nordtheme/vim",
        "rebelot/kanagawa.nvim",
        "rose-pine/neovim",
        "talha-akram/noctis.nvim",
        "vim-scripts/midnight.vim",
    },
    opts = {
        apply_scheme = true,
        plugin_strategy = nil,
        plugins = nil,
        colorschemes = {
            "catppuccin-mocha",
            "duskfox",
            "gruvbox-baby",
            "iceberg",
            "lunar",
            "mellow",
            "noctis_viola",
            "nord",
            "rose-pine-main",
            "sequoia-night",
            "tokyonight",
        },
        exclude_colorschemes = nil,
    },
}
